#!/bin/bash

# Diretório onde os repositórios serão clonados
TARGET_DIR="repos2"
mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"

# Lista de repositórios Java mais populares
REPOS=(
    "git@github.com:spring-projects/spring-framework.git"
    "git@github.com:spring-projects/spring-boot.git"
    "git@github.com:apache/tomcat.git"
    "git@github.com:apache/kafka.git"
    "git@github.com:apache/beam.git"
    "git@github.com:apache/hadoop.git"
    "git@github.com:eclipse/jetty.project.git"
    "git@github.com:netty/netty.git"
    "git@github.com:google/guava.git"
    "git@github.com:iluwatar/java-design-patterns.git"
    "git@github.com:bumptech/glide.git"
    "git@github.com:ReactiveX/RxJava.git"
    "git@github.com:square/retrofit.git"
    "git@github.com:apache/struts.git"
    "git@github.com:FasterXML/jackson.git"
    "git@github.com:google/gson.git"
    "git@github.com:apache/commons-lang.git"
    "git@github.com:apache/commons-io.git"
    "git@github.com:junit-team/junit5.git"
    "git@github.com:mockito/mockito.git"
    "git@github.com:apache/maven.git"
    "git@github.com:apache/logging-log4j2.git"
    "git@github.com:dropwizard/dropwizard.git"
    "git@github.com:google/dagger.git"
    "git@github.com:apache/groovy.git"
    "git@github.com:JetBrains/kotlin.git"
    "git@github.com:apache/poi.git"
    "git@github.com:apache/pdfbox.git"
    "git@github.com:apache/ignite.git"
    "git@github.com:raphw/byte-buddy.git"
    "git@github.com:checkstyle/checkstyle.git"
    "git@github.com:apache/camel.git"
    "git@github.com:apache/commons-collections.git"
    "git@github.com:apache/dubbo.git"
    "git@github.com:apache/hbase.git"
    "git@github.com:apache/nifi.git"
    "git@github.com:apache/shardingsphere.git"
    "git@github.com:apache/zookeeper.git"
    "git@github.com:bcgit/bc-java.git"
    "git@github.com:bitcoinj/bitcoinj.git"
    "git@github.com:cglib/cglib.git"
    "git@github.com:eclipse/eclipse.jdt.core.git"
    "git@github.com:eclipse/microprofile.git"
    "git@github.com:eclipse/swt.git"
    "git@github.com:google/auto.git"
    "git@github.com:google/error-prone.git"
    "git@github.com:google/j2objc.git"
    "git@github.com:google/truth.git"
    "git@github.com:hazelcast/hazelcast.git"
    "git@github.com:javaparser/javaparser.git"
    "git@github.com:jboss-developer/jboss-eap.git"
    "git@github.com:jOOQ/jOOQ.git"
    "git@github.com:jsoup/jsoup.git"
    "git@github.com:mybatis/mybatis-3.git"
    "git@github.com:oracle/graal.git"
    "git@github.com:oracle/opengrok.git"
    "git@github.com:oracle/visualvm.git"
    "git@github.com:perwendel/spark.git"
    "git@github.com:redisson/redisson.git"
    "git@github.com:square/okhttp.git"
    "git@github.com:square/picasso.git"
    "git@github.com:stevenschwenke/jug-dojo.git"
    "git@github.com:Tencent/angel.git"
    "git@github.com:Tencent/Firestorm.git"
    "git@github.com:Tencent/tinker.git"
    "git@github.com:x-stream/xstream.git"
    "git@github.com:yegor256/takes.git"
    "git@github.com:Netflix/Hystrix.git"
    "git@github.com:Netflix/SimianArmy.git"
    "git@github.com:Netflix/eureka.git"
    "git@github.com:Netflix/zuul.git"
    "git@github.com:jenkinsci/jenkins.git"
    "git@github.com:prestodb/presto.git"
    "git@github.com:elastic/elasticsearch.git"
    "git@github.com:hibernate/hibernate-orm.git"
    "git@github.com:apache/accumulo.git"
    "git@github.com:apache/storm.git"
    "git@github.com:apache/cassandra.git"
    "git@github.com:apache/rocketmq.git"
    "git@github.com:apache/flink.git"
    "git@github.com:apache/giraph.git"
    "git@github.com:apache/skywalking.git"
    "git@github.com:apache/druid.git"
    "git@github.com:apache/tika.git"
    "git@github.com:apache/opennlp.git"
    "git@github.com:apache/jmeter.git"
    "git@github.com:apache/phoenix.git"
    "git@github.com:apache/gora.git"
    "git@github.com:apache/tomee.git"
    "git@github.com:apache/logging-logback.git"
    "git@github.com:apache/zeppelin.git"
    "git@github.com:apache/airflow.git"
    "git@github.com:apache/beam-sdks.git"
    "git@github.com:apache/jspwiki.git"
)

# Clonar repositórios
for REPO in "${REPOS[@]}"; do
    echo "Clonando $REPO ..."
    git clone "$REPO"
done

echo "Todos os repositórios foram clonados!"

